### ISSUE TITLE
DBI Exception when using clipseqtools all

### ISSUE THREAD

**Issue by qizhijie** [mnsmar/clipseqtools#4]
Hi, there,

Thank you for creating the clipseqtools. It's my first time using this tool to analyzing clipseq data. I used clipseqtool-preprocess to preprocess my data. Then I tried to run 'clipseqtools all' as instructed by the website and encoutered the following error:

Validating arguments
Creating reads collection
Creating clusters and measuring size and score
 **DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: no such table: sample at /home/qizhijie/perl5/lib/perl5/GenOO/RegionCollection/Type/DBIC.pm line 172**

Do you have any idea/suggestion of how I should fix this?

Thanks,
Zhijie

**Comment by mnsmar** [comment]
Hi Zhijie,

The preprocess app attempts to load the aligned reads in an SQLite database. The default name for the database table is 'sample'. In your case this table name does not exist in the database (you can verify this by connecting on the database `sqlite3 [DB_FILE]` and running `.tables`). This means that probably something went wrong during database creation. To identify the preprocessing step that did not complete correctly you can start from the file `reads.adtrim.star_Aligned.out.single.sorted.collapsed.sam`. This is the file that is loaded in the database. Does this file look ok? If not, you can track previous files to locate which one is the first that looks "suspicious". If it looks fine then maybe the loading in the database failed. In either case you can use the individual commands of the preprocessing app to run the steps one after the other. By the way, I'm pretty sure that if something went wrong during preprocessing there should be some error reported. Did you see anything?

**Comment by qizhijie** [comment]
Thank you for replying. So I checked the tables using `sqlite3 ` and here's the case:
There are two `.db` files generated by preprocesss app, `reads.adtrim.star_Aligned.out.single.sorted.collapsed.db` and `reads.adtrim.star_Aligned.out.single.sorted.db`
According to the webstite, the one I used in my ``clipseqtool all --database` command is `sorted.db` for which 'sample' does not exist. I also checked `.sorted.sam` and it is empty.
But 'sample' does exist in `sorted.collapsed.db`.  And `.sorted.collapsed.sam` looks alright.
So should I change `--database sorted.db` into `--database sorted.collapsed.db` ? Is it a problem for '.sorted.sam' to be empty?
Thanks,
Zhijie

**Comment by mnsmar** [comment]
First, it seems there is a mistake in the instructions and indeed the correct database file is `reads.adtrim.star_Aligned.out.single.sorted.collapsed.db`. I'll have to fix this.

However the issue is quite confusing:
1. I don't see why there are two databases created. I look at the code and I cannot find any point where a second database could be created. Are you sure this file was created by the preprocessing script? Please check the file date.
2. It seems quite surprising that `.sorted.collapsed.sam` is fine while `.sorted.sam` is empty. The former is supposed to be produced by the latter. Is it possible that these files were created by an earlier failed run?

Yes the correct command would be to use
`--database reads.adtrim.star_Aligned.out.single.sorted.collapsed.db` but unless the previous two are resolved it will still fail as `reads.adtrim.star_Aligned.out.single.sorted.collapsed.db` is empty.

Which operating system are you using?

**Comment by qizhijie** [comment]
I checked other results from preprocess app and there is no `.sorted.db`. So I think you are correct that '.sorted.db' could be created by some earlier failed preprocess run or just by the failed clipseqtools run.
I was wrong about `.sorted.sam` was empty, it is not. I guess I mistakenly checked something else.
The clipseqtools command is running smoothly right now with '.sorted.collapsed.db' . So thank you for your help!

**Comment by mnsmar** [comment]
Great! You're welcome.
